config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :equipment
  resources :gears
  resources :alerts
  resources :items
  resources :accounts
  devise_for :users
  resources :equipment

  root :to => 'home#index'
  mount PostgresqlLoStreamer::Engine => '/gear_image'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :item
  belongs_to :account
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)
    @alert.item_id = current_user.account.items.ids
    @alert.account_id = current_user.account.id

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:date, :hasDoc, :status, :date_update, :date_cad, :item_id, :account_id)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @alert.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h4>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hasDoc, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :hasDoc, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :status, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_update, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date_update, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_cad, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date_cad, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :item, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :item, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :account, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :account, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<div class="page-header">
  <%= link_to alerts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @alert, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing alert</h1>
</div>

<%= render 'form' %>

app/views/alerts/index.html.erb
<div class="page-header">
  <%= link_to new_alert_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Alert
  <% end %>
  <h1>Listing alerts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Date</th>
            <th>Hasdoc</th>
            <th>Status</th>
            <th>Date update</th>
            <th>Date cad</th>
            <th>Item</th>
            <th>Account</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @alerts) do |alert| %>
            <td><%= alert.date %></td>
            <td><%= alert.hasDoc %></td>
            <td><%= alert.status %></td>
            <td><%= alert.date_update %></td>
            <td><%= alert.date_cad %></td>
            <td><%= alert.item %></td>
            <td><%= alert.account %></td>
            <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/alerts/new.html.erb
<div class="page-header">
  <%= link_to alerts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New alert</h1>
</div>

<%= render 'form' %>

app/views/alerts/show.html.erb
<div class="page-header">
  <%= link_to alerts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_alert_path(@alert), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show alert</h1>
</div>

<dl class="dl-horizontal">
  <dt>Date:</dt>
  <dd><%= @alert.date %></dd>

  <dt>Hasdoc:</dt>
  <dd><%= @alert.hasDoc %></dd>

  <dt>Status:</dt>
  <dd><%= @alert.status %></dd>

  <dt>Date update:</dt>
  <dd><%= @alert.date_update %></dd>

  <dt>Date cad:</dt>
  <dd><%= @alert.date_cad %></dd>

  <dt>Item:</dt>
  <dd><%= @alert.item %></dd>

  <dt>Account:</dt>
  <dd><%= @alert.account %></dd>

</dl>