config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :equipment
  resources :gears
  resources :alerts
  resources :items
  resources :accounts
  devise_for :users
  resources :equipment

  root :to => 'home#index'
  mount PostgresqlLoStreamer::Engine => '/gear_image'
end

app/models/gear.rb
class Gear < ActiveRecord::Base
belongs_to :item
belongs_to :Account
has many :equipments

mount_uploader :image, ItemsImageUploader 

end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)
    @gear.item_id = current_user.items.ids
    @gear.account_id = current_user.account.id

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.require(:gear).permit(:geartype, :model, :name, :serial, :color, 
      :brand, :details, :date_buy, :alert, :item_id, :account_id, :image)
    end
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/_form.html.erb
<%= form_for(@gear, html: { class: "form-horizontal", role: "form", :multipart => true }) do |f| %>
  <% if @gear.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@gear.errors.count, "error") %> prohibited this gear from being saved:</h4>

      <ul>
      <% @gear.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :geartype, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :geartype, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :model, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :model, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :serial, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :serial, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :color, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :color, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :brand, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :brand, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :details, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_buy, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date_buy, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :alert, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :alert, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :item_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :item_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :account_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :account_id, class: "form-control" %>
    </div>
  </div>
  <div class="field">
  <%= f.label :image, class: "col-sm-2 control-label"  %><br />
  <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/gears/edit.html.erb
<div class="page-header">
  <%= link_to gears_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @gear, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing gear</h1>
</div>

<%= render 'form' %>

app/views/gears/index.html.erb
<div class="page-header">
  <%= link_to new_gear_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Gear
  <% end %>
  <h1>Listing gears</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Gear Type</th>
            <th>Model</th>
            <th>Name</th>
            <th>Serial</th>
            <th>Color</th>
            <th>Brand</th>
            <th>Details</th>
            <th>Date buy</th>
            <th>Alert</th>
            <th>Item</th>
            <th>Account</th>
            <th>Imagem</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @gears) do |gear| %>
            <td><%= gear.geartype %></td>
            <td><%= gear.model %></td>
            <td><%= gear.name %></td>
            <td><%= gear.serial %></td>
            <td><%= gear.color %></td>
            <td><%= gear.brand %></td>
            <td><%= gear.details %></td>
            <td><%= gear.date_buy %></td>
            <td><%= gear.alert %></td>
            <td><%= gear.item_id %></td>
            <td><%= gear.account_id %></td>
            <td><%= gear.image_file_name %></td>
            <td><%= link_to 'Show', gear %></td>
        <td><%= link_to 'Edit', edit_gear_path(gear) %></td>
        <td><%= link_to 'Destroy', gear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/gears/new.html.erb
<div class="page-header">
  <%= link_to gears_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New gear</h1>
</div>

<%= render 'form' %>

app/views/gears/show.html.erb
<div class="page-header">
  <%= link_to gears_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_gear_path(@gear), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show gear</h1>
</div>

<dl class="dl-horizontal">
  <dt>Gear Type:</dt>
  <dd><%= @gear.geartype %></dd>

  <dt>Model:</dt>
  <dd><%= @gear.model %></dd>

  <dt>Name:</dt>
  <dd><%= @gear.name %></dd>

  <dt>Serial:</dt>
  <dd><%= @gear.serial %></dd>

  <dt>Color:</dt>
  <dd><%= @gear.color %></dd>

  <dt>Brand:</dt>
  <dd><%= @gear.brand %></dd>

  <dt>Details:</dt>
  <dd><%= @gear.details %></dd>

  <dt>Date buy:</dt>
  <dd><%= @gear.date_buy %></dd>

  <dt>Alert:</dt>
  <dd><%= @gear.alert %></dd>

  <dt>Item:</dt>
  <dd><%= @gear.item_id %></dd>

  <dt>Account:</dt>
  <dd><%= @gear.account_id %></dd>
  
  <dt>Imagem:</dt>
  <td><%= image_tag @gear.image %></td>
  

</dl>