config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :equipment
  resources :gears
  resources :alerts
  resources :items
  resources :accounts
  devise_for :users
  resources :equipment

  root :to => 'home#index'
  mount PostgresqlLoStreamer::Engine => '/gear_image'
end

app/models/search.rb
class Search < ActiveRecord::Base
    belongs_to :user
   
    def search_items
        
        items = Item.all
        items = items.where(["itemtp LIKE ?", "%#{itemtp}%"]) if itemtp.present?
        
        if itemtp == "GEAR"
            search_gears
        else
            search_equipments
        end
        
    end
    
    def search_gears
        
        gears = Gear.all
        gears = gears.where(["name LIKE ?", "%#{name}%"]) if name.present?
        gears = gears.where(["brand LIKE ?", "%#{brand}%"]) if brand.present?
        gears = gears.where(["model LIKE ?", "%#{model}%"]) if model.present?
        gears = gears.where(["color LIKE ?", "%#{color}%"]) if color.present?
        gears = gears.where(["details CONTAINS ?", "%#{details}%"]) if details.present?
        
        return gears
        
    end 
    
    def search_equipments
        
        equipments = Equipment.all
        equipments = equipments.where(["name LIKE ?", "%#{name}%"]) if name.present?
        equipments = equipments.where(["brand LIKE ?", "%#{brand}%"]) if brand.present?
        equipments = equipments.where(["model LIKE ?", "%#{model}%"]) if model.present?
        equipments = equipments.where(["color LIKE ?", "%#{color}%"]) if color.present?
        equipments = equipments.where(["details CONTAINS ?", "%#{details}%"]) if details.present?
        
        return equipments    
    end
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])
  end

  # GET /searches/new
  def new
    @search = Search.new
  end


  # POST /searches
  # POST /searches.json
  def create
    @search = Search.create(search_params)
    redirect_to @search
  end


  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:itemtp, :serial, :model, :name, :brand, :color, :details, :references)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/edit.html.erb
<div class="page-header">
  <%= link_to searches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @search, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing search</h1>
</div>

<%= render 'form' %>

app/views/searches/index.html.erb
<div class="page-header">
  <%= link_to new_search_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Search
  <% end %>
  <h1>Listing searches</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Itemtp</th>
            <th>Serial</th>
            <th>Model</th>
            <th>Name</th>
            <th>Brand</th>
            <th>Color</th>
            <th>Details</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @searches) do |search| %>
            <td><%= search.itemtp %></td>
            <td><%= search.serial %></td>
            <td><%= search.model %></td>
            <td><%= search.name %></td>
            <td><%= search.brand %></td>
            <td><%= search.color %></td>
            <td><%= search.details %></td>
            <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Search', search %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/searches/new.html.erb
<%= form_for(@search, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @search.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h4>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :itemtp, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :itemtp, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :serial, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :serial, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :model, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :model, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :brand, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :brand, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :color, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :color, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :details, class: "form-control" %>
    </div>
  </div>
  <div class="actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Search": "pure-button pute-button-primary" %>
    </div>
    <p>
      <%= link_to "Back", items_path %> 
    </p>  
  </div>
<% end %>

app/views/searches/show.html.erb
<div class="page-header">
  <%= link_to searches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>

  <h1>Show search</h1>
  <h2>
  <% if @search.search_items.empty? %>
  <p>No Records Found</p>
  <% else %>
  <% @search.search_items.each do |c| %>
  </h2>
</div>

<dl class="dl-horizontal">
  

  <dt>Serial:</dt>
  <dd><%= c.serial %></dd>

  <dt>Model:</dt>
  <dd><%= c.model %></dd>

  <dt>Name:</dt>
  <dd><%= c.name %></dd>

  <dt>Brand:</dt>
  <dd><%= c.brand %></dd>

  <dt>Color:</dt>
  <dd><%= c.color %></dd>

  <dt>Details:</dt>
  <dd><%= c.details %></dd>

</dl>
<% end %>
<% end %>