config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :equipment
  resources :gears
  resources :alerts
  resources :items
  resources :accounts
  devise_for :users
  resources :equipment

  root :to => 'home#index'
  mount PostgresqlLoStreamer::Engine => '/gear_image'
end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :Account
    belongs_to :User
    has_one :gear
    has_one :equipment, through: :gear
    
    def has_account
        return account_id.nil? == false
    end
    
    def self.search(search)
  
        if search
          where(["itemtp LIKE ?", "%#{search}%"])
        else
            all
        end
    end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :need_register, except: [:index]
  

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @item.account_id = current_user.account.id
    
    if @item.itemtp == "GEAR"
      redirect_to new_gear_path
    else
      redirect_to new_equipment_path
    end
    
  #  respond_to do |format|
   #   if @item.save
  #      format.html { redirect_to @item, notice: 'Item was successfully created.' }
  #      format.json { render :show, status: :created, location: @item }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @item.errors, status: :unprocessable_entity }
  #    end
  #  end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itemtp, :date_cad, :alert, :status, :user_id, :account_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Gear', class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.radio_button :itemtp, "GEAR",label: 'Gear',checked: true ,class: "form-control" %>
      <%= f.label 'Equipment', class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.radio_button :itemtp, "EQUIPMENT",label: 'Equipment' ,class: "form-control" %>
    </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :alert, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :alert, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :status, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing item</h1>
</div>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Item
  <% end %>
  <h1>Listing items</h1>
  <h2>
    <tr>
  <%= form_tag items_path, :method => "get" do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Itens" %>
  <%= submit_tag "Search"%>
  <% end %>
  </tr>
  </h2>
  <h3 class="searchLinks">
  <tr>
    <%= link_to "Custom Search" + " /", new_search_path %>
  </tr>
  <tr>
    <%= link_to "Saved Searches", "searches" %>
  </tr>
  </h3>
  <h4>
  <tr>
    <%= link_to "Alert", "alerts" %>
  </tr>
  </h4>
  
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Item Type</th>
            <th>name</th>
            <th>brand</th>
            <th>model</th>
            <th>color</th>
            <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @items) do |item| %>
            <td><%= item.itemtp %></td>
            <td><%= item.alert %></td>
            <td><%= item.status %></td>
            <td><%= link_to 'Show', item %></td>
            
           
        
            
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Type:</dt>
  <dd><%= @item.itemtp %></dd>

  <dt>Alert:</dt>
  <dd><%= @item.alert %></dd>

  <dt>Status:</dt>
  <dd><%= @item.status %></dd>

</dl>